package com.example.khoitriso.utils

/**
 * Enum class representing all message codes from the backend API
 * Used to map backend message codes to localized string resources
 */
enum class MessageCode(val code: String) {
    // ===== SUCCESS MESSAGES =====
    SUCCESS("SUCCESS"),
    CREATED_SUCCESS("CREATED_SUCCESS"),
    UPDATED_SUCCESS("UPDATED_SUCCESS"),
    DELETED_SUCCESS("DELETED_SUCCESS"),

    // ===== AUTH MESSAGES =====
    LOGIN_SUCCESS("LOGIN_SUCCESS"),
    LOGOUT_SUCCESS("LOGOUT_SUCCESS"),
    REGISTER_SUCCESS("REGISTER_SUCCESS"),
    REFRESH_TOKEN_SUCCESS("REFRESH_TOKEN_SUCCESS"),
    PASSWORD_CHANGED_SUCCESS("PASSWORD_CHANGED_SUCCESS"),
    PASSWORD_RESET_SUCCESS("PASSWORD_RESET_SUCCESS"),
    EMAIL_VERIFIED_SUCCESS("EMAIL_VERIFIED_SUCCESS"),
    PROFILE_UPDATED_SUCCESS("PROFILE_UPDATED_SUCCESS"),
    PROFILE_RETRIEVED_SUCCESS("PROFILE_RETRIEVED_SUCCESS"),
    OAUTH_SUCCESS("OAUTH_SUCCESS"),
    GOOGLE_SDK_LOGIN_SUCCESS("GOOGLE_SDK_LOGIN_SUCCESS"),
    FACEBOOK_SDK_LOGIN_SUCCESS("FACEBOOK_SDK_LOGIN_SUCCESS"),

    // ===== USER MESSAGES =====
    USER_CREATED_SUCCESS("USER_CREATED_SUCCESS"),
    USER_UPDATED_SUCCESS("USER_UPDATED_SUCCESS"),
    USER_DELETED_SUCCESS("USER_DELETED_SUCCESS"),
    USER_LIST_SUCCESS("USER_LIST_SUCCESS"),
    USER_DETAIL_SUCCESS("USER_DETAIL_SUCCESS"),
    AVATAR_UPDATED_SUCCESS("AVATAR_UPDATED_SUCCESS"),

    // ===== COURSE MESSAGES =====
    COURSE_CREATED_SUCCESS("COURSE_CREATED_SUCCESS"),
    COURSE_UPDATED_SUCCESS("COURSE_UPDATED_SUCCESS"),
    COURSE_DELETED_SUCCESS("COURSE_DELETED_SUCCESS"),
    COURSE_LIST_SUCCESS("COURSE_LIST_SUCCESS"),
    COURSE_DETAIL_SUCCESS("COURSE_DETAIL_SUCCESS"),
    COURSE_ENROLLED_SUCCESS("COURSE_ENROLLED_SUCCESS"),
    COURSE_SUBMITTED_FOR_REVIEW_SUCCESS("COURSE_SUBMITTED_FOR_REVIEW_SUCCESS"),
    ENROLLMENT_SUCCESS("ENROLLMENT_SUCCESS"),
    UNENROLLMENT_SUCCESS("UNENROLLMENT_SUCCESS"),
    ENROLLMENT_NOT_FOUND("ENROLLMENT_NOT_FOUND"),
    ALREADY_ENROLLED("ALREADY_ENROLLED"),
    PAYMENT_REQUIRED("PAYMENT_REQUIRED"),

    // ===== CATEGORY MESSAGES =====
    CATEGORY_CREATED_SUCCESS("CATEGORY_CREATED_SUCCESS"),
    CATEGORY_UPDATED_SUCCESS("CATEGORY_UPDATED_SUCCESS"),
    CATEGORY_DELETED_SUCCESS("CATEGORY_DELETED_SUCCESS"),
    CATEGORY_LIST_SUCCESS("CATEGORY_LIST_SUCCESS"),
    CATEGORY_DETAIL_SUCCESS("CATEGORY_DETAIL_SUCCESS"),

    // ===== CART MESSAGES =====
    CART_ITEM_ADDED_SUCCESS("CART_ITEM_ADDED_SUCCESS"),
    CART_ITEM_UPDATED_SUCCESS("CART_ITEM_UPDATED_SUCCESS"),
    CART_ITEM_DELETED_SUCCESS("CART_ITEM_DELETED_SUCCESS"),
    CART_CLEARED_SUCCESS("CART_CLEARED_SUCCESS"),
    CART_LIST_SUCCESS("CART_LIST_SUCCESS"),

    // ===== ORDER MESSAGES =====
    ORDER_CREATED_SUCCESS("ORDER_CREATED_SUCCESS"),
    ORDER_UPDATED_SUCCESS("ORDER_UPDATED_SUCCESS"),
    ORDER_CANCELLED_SUCCESS("ORDER_CANCELLED_SUCCESS"),
    ORDER_LIST_SUCCESS("ORDER_LIST_SUCCESS"),
    ORDER_DETAIL_SUCCESS("ORDER_DETAIL_SUCCESS"),
    ORDER_STATUS_UPDATED_SUCCESS("ORDER_STATUS_UPDATED_SUCCESS"),
    ORDER_PAYMENT_PROCESSED_SUCCESS("ORDER_PAYMENT_PROCESSED_SUCCESS"),
    ORDER_NOT_FOUND("ORDER_NOT_FOUND"),
    VNPAY_PAYMENT_URL_SUCCESS("VNPAY_PAYMENT_URL_SUCCESS"),
    VNPAY_QUERY_SUCCESS("VNPAY_QUERY_SUCCESS"),
    VNPAY_QUERY_FAILED("VNPAY_QUERY_FAILED"),
    VNPAY_STATUS_SUCCESS("VNPAY_STATUS_SUCCESS"),

    // ===== COUPON MESSAGES =====
    COUPON_CREATED_SUCCESS("COUPON_CREATED_SUCCESS"),
    COUPON_UPDATED_SUCCESS("COUPON_UPDATED_SUCCESS"),
    COUPON_DELETED_SUCCESS("COUPON_DELETED_SUCCESS"),
    COUPON_LIST_SUCCESS("COUPON_LIST_SUCCESS"),
    COUPON_DETAIL_SUCCESS("COUPON_DETAIL_SUCCESS"),
    COUPON_VALID_SUCCESS("COUPON_VALID_SUCCESS"),
    COUPON_INVALID("COUPON_INVALID"),
    COUPON_NOT_FOUND("COUPON_NOT_FOUND"),
    COUPON_ALREADY_EXISTS("COUPON_ALREADY_EXISTS"),

    // ===== LEARNING PATH MESSAGES =====
    LEARNING_PATH_CREATED_SUCCESS("LEARNING_PATH_CREATED_SUCCESS"),
    LEARNING_PATH_UPDATED_SUCCESS("LEARNING_PATH_UPDATED_SUCCESS"),
    LEARNING_PATH_DELETED_SUCCESS("LEARNING_PATH_DELETED_SUCCESS"),
    LEARNING_PATH_LIST_SUCCESS("LEARNING_PATH_LIST_SUCCESS"),
    LEARNING_PATH_DETAIL_SUCCESS("LEARNING_PATH_DETAIL_SUCCESS"),
    LEARNING_PATH_COURSES_SUCCESS("LEARNING_PATH_COURSES_SUCCESS"),
    LEARNING_PATH_COURSE_ADDED_SUCCESS("LEARNING_PATH_COURSE_ADDED_SUCCESS"),
    LEARNING_PATH_COURSE_REMOVED_SUCCESS("LEARNING_PATH_COURSE_REMOVED_SUCCESS"),
    LEARNING_PATH_COURSE_UPDATED_SUCCESS("LEARNING_PATH_COURSE_UPDATED_SUCCESS"),
    LEARNING_PATH_ENROLLED_SUCCESS("LEARNING_PATH_ENROLLED_SUCCESS"),
    LEARNING_PATH_ALREADY_ENROLLED("LEARNING_PATH_ALREADY_ENROLLED"),
    LEARNING_PATH_NOT_FOUND("LEARNING_PATH_NOT_FOUND"),
    LEARNING_PATH_COURSE_ALREADY_EXISTS("LEARNING_PATH_COURSE_ALREADY_EXISTS"),
    LEARNING_PATH_COURSE_NOT_FOUND("LEARNING_PATH_COURSE_NOT_FOUND"),

    // ===== WISHLIST MESSAGES =====
    WISHLIST_ITEM_ADDED_SUCCESS("WISHLIST_ITEM_ADDED_SUCCESS"),
    WISHLIST_ITEM_DELETED_SUCCESS("WISHLIST_ITEM_DELETED_SUCCESS"),
    WISHLIST_LIST_SUCCESS("WISHLIST_LIST_SUCCESS"),

    // ===== REVIEW MESSAGES =====
    REVIEW_CREATED_SUCCESS("REVIEW_CREATED_SUCCESS"),
    REVIEW_UPDATED_SUCCESS("REVIEW_UPDATED_SUCCESS"),
    REVIEW_DELETED_SUCCESS("REVIEW_DELETED_SUCCESS"),
    REVIEW_LIST_SUCCESS("REVIEW_LIST_SUCCESS"),
    REVIEW_ALREADY_EXISTS("REVIEW_ALREADY_EXISTS"),
    REVIEW_NOT_FOUND("REVIEW_NOT_FOUND"),

    // ===== NOTIFICATION MESSAGES =====
    NOTIFICATION_CREATED_SUCCESS("NOTIFICATION_CREATED_SUCCESS"),
    NOTIFICATION_LIST_SUCCESS("NOTIFICATION_LIST_SUCCESS"),
    NOTIFICATION_READ_SUCCESS("NOTIFICATION_READ_SUCCESS"),
    NOTIFICATION_DELETED_SUCCESS("NOTIFICATION_DELETED_SUCCESS"),
    NOTIFICATION_NOT_FOUND("NOTIFICATION_NOT_FOUND"),

    // ===== NOTIFICATION CONTENT MESSAGES (Prefix: Noti_) =====
    // Course Notifications - Titles
    NOTI_TITLE_COURSE_ENROLLED("Noti_Title_COURSE_ENROLLED"),
    NOTI_TITLE_COURSE_COMPLETED("Noti_Title_COURSE_COMPLETED"),
    NOTI_TITLE_COURSE_NEW_LESSON("Noti_Title_COURSE_NEW_LESSON"),
    NOTI_TITLE_COURSE_APPROVED("Noti_Title_COURSE_APPROVED"),
    NOTI_TITLE_COURSE_REJECTED("Noti_Title_COURSE_REJECTED"),

    // Course Notifications - Messages
    NOTI_COURSE_ENROLLED("Noti_COURSE_ENROLLED"),
    NOTI_COURSE_COMPLETED("Noti_COURSE_COMPLETED"),
    NOTI_COURSE_NEW_LESSON("Noti_COURSE_NEW_LESSON"),
    NOTI_COURSE_APPROVED("Noti_COURSE_APPROVED"),
    NOTI_COURSE_REJECTED("Noti_COURSE_REJECTED"),

    // Order & Payment Notifications - Titles
    NOTI_TITLE_ORDER_CREATED("Noti_Title_ORDER_CREATED"),
    NOTI_TITLE_ORDER_PAID("Noti_Title_ORDER_PAID"),
    NOTI_TITLE_ORDER_CANCELLED("Noti_Title_ORDER_CANCELLED"),

    // Order & Payment Notifications - Messages
    NOTI_ORDER_CREATED("Noti_ORDER_CREATED"),
    NOTI_ORDER_PAID("Noti_ORDER_PAID"),
    NOTI_ORDER_CANCELLED("Noti_ORDER_CANCELLED"),

    // Certificate Notifications - Titles
    NOTI_TITLE_CERTIFICATE_ISSUED("Noti_Title_CERTIFICATE_ISSUED"),

    // Certificate Notifications - Messages
    NOTI_CERTIFICATE_ISSUED("Noti_CERTIFICATE_ISSUED"),

    // Assignment Notifications - Titles
    NOTI_TITLE_ASSIGNMENT_NEW("Noti_Title_ASSIGNMENT_NEW"),
    NOTI_TITLE_ASSIGNMENT_GRADED("Noti_Title_ASSIGNMENT_GRADED"),
    NOTI_TITLE_ASSIGNMENT_DUE_SOON("Noti_Title_ASSIGNMENT_DUE_SOON"),

    // Assignment Notifications - Messages
    NOTI_ASSIGNMENT_NEW("Noti_ASSIGNMENT_NEW"),
    NOTI_ASSIGNMENT_GRADED("Noti_ASSIGNMENT_GRADED"),
    NOTI_ASSIGNMENT_DUE_SOON("Noti_ASSIGNMENT_DUE_SOON"),

    // Lesson Notifications - Titles
    NOTI_TITLE_LESSON_COMPLETED("Noti_Title_LESSON_COMPLETED"),
    NOTI_TITLE_LESSON_DISCUSSION_REPLY("Noti_Title_LESSON_DISCUSSION_REPLY"),

    // Lesson Notifications - Messages
    NOTI_LESSON_COMPLETED("Noti_LESSON_COMPLETED"),
    NOTI_LESSON_DISCUSSION_REPLY("Noti_LESSON_DISCUSSION_REPLY"),

    // Book Notifications - Titles
    NOTI_TITLE_BOOK_ACTIVATED("Noti_Title_BOOK_ACTIVATED"),
    NOTI_TITLE_BOOK_APPROVED("Noti_Title_BOOK_APPROVED"),
    NOTI_TITLE_BOOK_REJECTED("Noti_Title_BOOK_REJECTED"),

    // Book Notifications - Messages
    NOTI_BOOK_ACTIVATED("Noti_BOOK_ACTIVATED"),
    NOTI_BOOK_APPROVED("Noti_BOOK_APPROVED"),
    NOTI_BOOK_REJECTED("Noti_BOOK_REJECTED"),

    // LiveClass Notifications - Titles
    NOTI_TITLE_LIVE_CLASS_SCHEDULED("Noti_Title_LIVE_CLASS_SCHEDULED"),
    NOTI_TITLE_LIVE_CLASS_STARTING("Noti_Title_LIVE_CLASS_STARTING"),
    NOTI_TITLE_LIVE_CLASS_STARTED("Noti_Title_LIVE_CLASS_STARTED"),

    // LiveClass Notifications - Messages
    NOTI_LIVE_CLASS_SCHEDULED("Noti_LIVE_CLASS_SCHEDULED"),
    NOTI_LIVE_CLASS_STARTING("Noti_LIVE_CLASS_STARTING"),
    NOTI_LIVE_CLASS_STARTED("Noti_LIVE_CLASS_STARTED"),

    // LearningPath Notifications - Titles
    NOTI_TITLE_LEARNING_PATH_ENROLLED("Noti_Title_LEARNING_PATH_ENROLLED"),
    NOTI_TITLE_LEARNING_PATH_COMPLETED("Noti_Title_LEARNING_PATH_COMPLETED"),

    // LearningPath Notifications - Messages
    NOTI_LEARNING_PATH_ENROLLED("Noti_LEARNING_PATH_ENROLLED"),
    NOTI_LEARNING_PATH_COMPLETED("Noti_LEARNING_PATH_COMPLETED"),

    // Forum Notifications - Titles
    NOTI_TITLE_FORUM_QUESTION_ANSWERED("Noti_Title_FORUM_QUESTION_ANSWERED"),
    NOTI_TITLE_FORUM_ANSWER_ACCEPTED("Noti_Title_FORUM_ANSWER_ACCEPTED"),

    // Forum Notifications - Messages
    NOTI_FORUM_QUESTION_ANSWERED("Noti_FORUM_QUESTION_ANSWERED"),
    NOTI_FORUM_ANSWER_ACCEPTED("Noti_FORUM_ANSWER_ACCEPTED"),

    // Forum Error Messages
    ANSWER_NOT_ACCEPTED("ANSWER_NOT_ACCEPTED"),

    // Review Notifications - Titles
    NOTI_TITLE_REVIEW_REPLIED("Noti_Title_REVIEW_REPLIED"),
    NOTI_TITLE_REVIEW_HELPFUL_MILESTONE("Noti_Title_REVIEW_HELPFUL_MILESTONE"),

    // Review Notifications - Messages
    NOTI_REVIEW_REPLIED("Noti_REVIEW_REPLIED"),
    NOTI_REVIEW_HELPFUL_MILESTONE("Noti_REVIEW_HELPFUL_MILESTONE"),

    // Wishlist Notifications - Titles
    NOTI_TITLE_WISHLIST_ON_SALE("Noti_Title_WISHLIST_ON_SALE"),

    // Wishlist Notifications - Messages
    NOTI_WISHLIST_ON_SALE("Noti_WISHLIST_ON_SALE"),

    // Coupon Notifications - Titles
    NOTI_TITLE_COUPON_APPLIED("Noti_Title_COUPON_APPLIED"),
    NOTI_TITLE_COUPON_EXPIRING("Noti_Title_COUPON_EXPIRING"),

    // Coupon Notifications - Messages
    NOTI_COUPON_APPLIED("Noti_COUPON_APPLIED"),
    NOTI_COUPON_EXPIRING("Noti_COUPON_EXPIRING"),

    // System Notifications - Titles
    NOTI_TITLE_SYSTEM_ANNOUNCEMENT("Noti_Title_SYSTEM_ANNOUNCEMENT"),
    NOTI_TITLE_SYSTEM_MAINTENANCE("Noti_Title_SYSTEM_MAINTENANCE"),

    // System Notifications - Messages
    NOTI_SYSTEM_ANNOUNCEMENT("Noti_SYSTEM_ANNOUNCEMENT"),
    NOTI_SYSTEM_MAINTENANCE("Noti_SYSTEM_MAINTENANCE"),

    // ===== LESSON MESSAGES =====
    LESSON_CREATED_SUCCESS("LESSON_CREATED_SUCCESS"),
    LESSON_UPDATED_SUCCESS("LESSON_UPDATED_SUCCESS"),
    LESSON_DELETED_SUCCESS("LESSON_DELETED_SUCCESS"),
    LESSON_NOT_FOUND("LESSON_NOT_FOUND"),
    LESSON_PROGRESS_UPDATED_SUCCESS("LESSON_PROGRESS_UPDATED_SUCCESS"),
    VIDEO_PROGRESS_RETRIEVED_SUCCESS("VIDEO_PROGRESS_RETRIEVED_SUCCESS"),
    VIDEO_PROGRESS_UPDATED_SUCCESS("VIDEO_PROGRESS_UPDATED_SUCCESS"),

    // ===== ASSIGNMENT MESSAGES =====
    ASSIGNMENT_CREATED_SUCCESS("ASSIGNMENT_CREATED_SUCCESS"),
    ASSIGNMENT_UPDATED_SUCCESS("ASSIGNMENT_UPDATED_SUCCESS"),
    ASSIGNMENT_DELETED_SUCCESS("ASSIGNMENT_DELETED_SUCCESS"),
    ASSIGNMENT_NOT_FOUND("ASSIGNMENT_NOT_FOUND"),
    ASSIGNMENT_LIST_SUCCESS("ASSIGNMENT_LIST_SUCCESS"),
    ASSIGNMENT_DETAIL_SUCCESS("ASSIGNMENT_DETAIL_SUCCESS"),
    QUESTION_ADDED_TO_ASSIGNMENT_SUCCESS("QUESTION_ADDED_TO_ASSIGNMENT_SUCCESS"),
    QUESTION_REMOVED_FROM_ASSIGNMENT_SUCCESS("QUESTION_REMOVED_FROM_ASSIGNMENT_SUCCESS"),
    QUESTION_NOT_FOUND("QUESTION_NOT_FOUND"),
    QUESTION_UPDATED_SUCCESS("QUESTION_UPDATED_SUCCESS"),
    QUESTION_CREATED_SUCCESS("QUESTION_CREATED_SUCCESS"),
    QUESTIONS_CREATED_SUCCESS("QUESTIONS_CREATED_SUCCESS"),
    ASSIGNMENT_SUBMITTED_SUCCESS("ASSIGNMENT_SUBMITTED_SUCCESS"),
    ASSIGNMENT_GRADED_SUCCESS("ASSIGNMENT_GRADED_SUCCESS"),
    MAX_ATTEMPTS_EXCEEDED("MAX_ATTEMPTS_EXCEEDED"),
    ATTEMPT_NOT_FOUND("ATTEMPT_NOT_FOUND"),
    ASSIGNMENT_DUE_DATE_PASSED("ASSIGNMENT_DUE_DATE_PASSED"),
    INVALID_DEFAULT_POINTS_CONFIGURATION("INVALID_DEFAULT_POINTS_CONFIGURATION"),
    TOTAL_POINTS_MUST_EQUAL_TEN("TOTAL_POINTS_MUST_EQUAL_TEN"),
    ASSIGNMENT_ANSWERS_NOT_AVAILABLE("ASSIGNMENT_ANSWERS_NOT_AVAILABLE"),
    ASSIGNMENT_ATTEMPT_IN_PROGRESS("ASSIGNMENT_ATTEMPT_IN_PROGRESS"),
    ASSIGNMENT_TIME_LIMIT_EXCEEDED("ASSIGNMENT_TIME_LIMIT_EXCEEDED"),
    ASSIGNMENT_ATTEMPT_ALREADY_COMPLETED("ASSIGNMENT_ATTEMPT_ALREADY_COMPLETED"),
    ASSIGNMENT_BATCH_GRADED_SUCCESS("ASSIGNMENT_BATCH_GRADED_SUCCESS"),

    // ===== LESSON MATERIAL MESSAGES =====
    LESSON_MATERIAL_CREATED_SUCCESS("LESSON_MATERIAL_CREATED_SUCCESS"),
    LESSON_MATERIAL_UPDATED_SUCCESS("LESSON_MATERIAL_UPDATED_SUCCESS"),
    LESSON_MATERIAL_DELETED_SUCCESS("LESSON_MATERIAL_DELETED_SUCCESS"),
    LESSON_MATERIAL_NOT_FOUND("LESSON_MATERIAL_NOT_FOUND"),
    LESSON_MATERIAL_LIST_SUCCESS("LESSON_MATERIAL_LIST_SUCCESS"),

    // ===== DISCUSSION MESSAGES =====
    DISCUSSION_CREATED_SUCCESS("DISCUSSION_CREATED_SUCCESS"),
    DISCUSSION_UPDATED_SUCCESS("DISCUSSION_UPDATED_SUCCESS"),
    DISCUSSION_DELETED_SUCCESS("DISCUSSION_DELETED_SUCCESS"),
    DISCUSSION_NOT_FOUND("DISCUSSION_NOT_FOUND"),
    REPLY_CREATED_SUCCESS("REPLY_CREATED_SUCCESS"),
    DISCUSSION_LIKE_SUCCESS("DISCUSSION_LIKE_SUCCESS"),
    DISCUSSION_UNLIKE_SUCCESS("DISCUSSION_UNLIKE_SUCCESS"),
    LIKE_UPDATED_SUCCESS("LIKE_UPDATED_SUCCESS"),

    // ===== LIVE CLASS MESSAGES =====
    LIVE_CLASS_CREATED_SUCCESS("LIVE_CLASS_CREATED_SUCCESS"),
    LIVE_CLASS_UPDATED_SUCCESS("LIVE_CLASS_UPDATED_SUCCESS"),
    LIVE_CLASS_DELETED_SUCCESS("LIVE_CLASS_DELETED_SUCCESS"),
    LIVE_CLASS_NOT_FOUND("LIVE_CLASS_NOT_FOUND"),
    LIVE_CLASS_JOINED_SUCCESS("LIVE_CLASS_JOINED_SUCCESS"),
    LIVE_CLASS_LEFT_SUCCESS("LIVE_CLASS_LEFT_SUCCESS"),
    LIVE_CLASS_FULL("LIVE_CLASS_FULL"),
    LIVE_CLASS_NOT_STARTED("LIVE_CLASS_NOT_STARTED"),
    LIVE_CLASS_ENDED("LIVE_CLASS_ENDED"),
    LIVE_CLASS_ALREADY_JOINED("LIVE_CLASS_ALREADY_JOINED"),
    LIVE_CLASS_PARTICIPATION_NOT_FOUND("LIVE_CLASS_PARTICIPATION_NOT_FOUND"),
    LIVE_CLASS_HAS_PARTICIPANTS("LIVE_CLASS_HAS_PARTICIPANTS"),
    LIVE_CLASS_INSTRUCTOR_ONLY("LIVE_CLASS_INSTRUCTOR_ONLY"),

    // ===== CERTIFICATE MESSAGES =====
    CERTIFICATE_GENERATED_SUCCESS("CERTIFICATE_GENERATED_SUCCESS"),
    CERTIFICATE_NOT_FOUND("CERTIFICATE_NOT_FOUND"),
    CERTIFICATE_VERIFIED_SUCCESS("CERTIFICATE_VERIFIED_SUCCESS"),
    CERTIFICATE_REQUIREMENTS_NOT_MET("CERTIFICATE_REQUIREMENTS_NOT_MET"),

    // ===== ANALYTICS MESSAGES =====
    ANALYTICS_DASHBOARD_SUCCESS("ANALYTICS_DASHBOARD_SUCCESS"),
    ANALYTICS_COURSE_SUCCESS("ANALYTICS_COURSE_SUCCESS"),
    ANALYTICS_INSTRUCTOR_SUCCESS("ANALYTICS_INSTRUCTOR_SUCCESS"),
    INVALID_PERIOD("INVALID_PERIOD"),

    // ===== BACKUP MESSAGES =====
    BACKUP_CREATED_SUCCESS("BACKUP_CREATED_SUCCESS"),
    BACKUP_LIST_SUCCESS("BACKUP_LIST_SUCCESS"),
    BACKUP_DETAIL_SUCCESS("BACKUP_DETAIL_SUCCESS"),
    BACKUP_DELETED_SUCCESS("BACKUP_DELETED_SUCCESS"),
    BACKUP_DOWNLOAD_SUCCESS("BACKUP_DOWNLOAD_SUCCESS"),
    BACKUP_RESTORE_SUCCESS("BACKUP_RESTORE_SUCCESS"),
    BACKUP_SETTINGS_UPDATED_SUCCESS("BACKUP_SETTINGS_UPDATED_SUCCESS"),
    BACKUP_IN_PROGRESS("BACKUP_IN_PROGRESS"),
    BACKUP_FAILED("BACKUP_FAILED"),
    BACKUP_NOT_FOUND("BACKUP_NOT_FOUND"),
    BACKUP_RESTORE_FAILED("BACKUP_RESTORE_FAILED"),
    BACKUP_RESTORE_CONFIRMATION_REQUIRED("BACKUP_RESTORE_CONFIRMATION_REQUIRED"),

    // ===== ERROR MESSAGES =====
    // Validation Errors
    VALIDATION_ERROR("VALIDATION_ERROR"),
    INVALID_INPUT("INVALID_INPUT"),
    INVALID_EMAIL("INVALID_EMAIL"),
    INVALID_PASSWORD("INVALID_PASSWORD"),
    INVALID_PHONE_NUMBER("INVALID_PHONE_NUMBER"),
    INVALID_PHONE_FORMAT("INVALID_PHONE_FORMAT"),
    INVALID_LANGUAGE("INVALID_LANGUAGE"),
    INVALID_TIMEZONE("INVALID_TIMEZONE"),
    FILE_REQUIRED("FILE_REQUIRED"),
    INVALID_FILE_TYPE("INVALID_FILE_TYPE"),
    FILE_TOO_LARGE("FILE_TOO_LARGE"),

    // Authentication Errors
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    TOKEN_EXPIRED("TOKEN_EXPIRED"),
    TOKEN_INVALID("TOKEN_INVALID"),
    REFRESH_TOKEN_INVALID("REFRESH_TOKEN_INVALID"),
    REFRESH_TOKEN_EXPIRED("REFRESH_TOKEN_EXPIRED"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    ACCOUNT_LOCKED("ACCOUNT_LOCKED"),
    ACCOUNT_NOT_VERIFIED("ACCOUNT_NOT_VERIFIED"),
    OAUTH_INVALID_STATE_OR_CODE("OAUTH_INVALID_STATE_OR_CODE"),
    OAUTH_TOKEN_EXCHANGE_FAILED("OAUTH_TOKEN_EXCHANGE_FAILED"),
    OAUTH_INVALID_TOKEN_RESPONSE("OAUTH_INVALID_TOKEN_RESPONSE"),
    OAUTH_FAILED_FETCH_USER_INFO("OAUTH_FAILED_FETCH_USER_INFO"),
    FACEBOOK_CLIENTID_NOT_CONFIGURED("FACEBOOK_CLIENTID_NOT_CONFIGURED"),
    FACEBOOK_CLIENTSECRET_NOT_CONFIGURED("FACEBOOK_CLIENTSECRET_NOT_CONFIGURED"),
    FACEBOOK_EMAIL_PERMISSION_REQUIRED("FACEBOOK_EMAIL_PERMISSION_REQUIRED"),
    STUDENT_MUST_USE_OAUTH("STUDENT_MUST_USE_OAUTH"),
    RESET_TOKEN_INVALID("RESET_TOKEN_INVALID"),
    RESET_TOKEN_EXPIRED("RESET_TOKEN_EXPIRED"),
    EMAIL_VERIFICATION_TOKEN_INVALID("EMAIL_VERIFICATION_TOKEN_INVALID"),
    EMAIL_VERIFICATION_TOKEN_EXPIRED("EMAIL_VERIFICATION_TOKEN_EXPIRED"),
    REGISTER_FAILED("REGISTER_FAILED"),
    PASSWORD_CHANGE_FAILED("PASSWORD_CHANGE_FAILED"),
    USER_DOES_NOT_EXIST("USER_DOES_NOT_EXIST"),
    USERNAME_EMAIL_EXISTS("USERNAME_EMAIL_EXISTS"),
    PASSWORD_NOT_STRONG_ENOUGH("PASSWORD_NOT_STRONG_ENOUGH"),
    CURRENT_PASSWORD_INCORRECT("CURRENT_PASSWORD_INCORRECT"),

    // Resource Errors
    NOT_FOUND("NOT_FOUND"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    COURSE_NOT_FOUND("COURSE_NOT_FOUND"),
    CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND"),
    CART_ITEM_NOT_FOUND("CART_ITEM_NOT_FOUND"),

    // Business Logic Errors
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
    USERNAME_ALREADY_EXISTS("USERNAME_ALREADY_EXISTS"),
    WEAK_PASSWORD("WEAK_PASSWORD"),
    PASSWORD_MISMATCH("PASSWORD_MISMATCH"),
    COURSE_ALREADY_ENROLLED("COURSE_ALREADY_ENROLLED"),
    INSUFFICIENT_PERMISSION("INSUFFICIENT_PERMISSION"),
    ITEM_ALREADY_IN_CART("ITEM_ALREADY_IN_CART"),
    ITEM_ALREADY_IN_WISHLIST("ITEM_ALREADY_IN_WISHLIST"),

    // System Errors
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    DATABASE_ERROR("DATABASE_ERROR"),
    EXTERNAL_SERVICE_ERROR("EXTERNAL_SERVICE_ERROR"),

    // Rate Limiting
    RATE_LIMIT_EXCEEDED("RATE_LIMIT_EXCEEDED"),
    TOO_MANY_REQUESTS("TOO_MANY_REQUESTS"),

    // Settings
    SETTINGS_UPDATED_SUCCESS("SETTINGS_UPDATED_SUCCESS"),
    SETTING_CREATED_SUCCESS("SETTING_CREATED_SUCCESS"),
    SETTING_KEY_ALREADY_EXISTS("SETTING_KEY_ALREADY_EXISTS"),

    // ===== FILE/UPLOAD MESSAGES =====
    UPLOAD_SUCCESS("UPLOAD_SUCCESS"),
    UPLOAD_FAILED("UPLOAD_FAILED"),
    PRESIGNED_URL_GENERATED("PRESIGNED_URL_GENERATED"),
    FILE_DELETED_SUCCESS("FILE_DELETED_SUCCESS"),
    FILE_DELETE_FAILED("FILE_DELETE_FAILED"),
    FILE_NOT_FOUND("FILE_NOT_FOUND"),
    BATCH_DELETE_FAILED("BATCH_DELETE_FAILED"),
    FILE_CLEANUP_SUCCESS("FILE_CLEANUP_SUCCESS"),
    FILE_CREATED_SUCCESS("FILE_CREATED_SUCCESS"),
    FILE_CREATE_FAILED("FILE_CREATE_FAILED"),
    FILE_UPDATED_SUCCESS("FILE_UPDATED_SUCCESS"),
    FILE_UPDATE_FAILED("FILE_UPDATE_FAILED"),
    FILE_COPIED_SUCCESS("FILE_COPIED_SUCCESS"),
    FILE_COPY_FAILED("FILE_COPY_FAILED"),

    // ===== BOOK MESSAGES =====
    BOOK_CREATED_SUCCESS("BOOK_CREATED_SUCCESS"),
    BOOK_UPDATED_SUCCESS("BOOK_UPDATED_SUCCESS"),
    BOOK_DELETED_SUCCESS("BOOK_DELETED_SUCCESS"),
    BOOK_NOT_FOUND("BOOK_NOT_FOUND"),
    BOOK_QUESTION_CREATED_SUCCESS("BOOK_QUESTION_CREATED_SUCCESS"),
    BOOK_QUESTION_UPDATED_SUCCESS("BOOK_QUESTION_UPDATED_SUCCESS"),
    BOOK_SOLUTION_CREATED_SUCCESS("BOOK_SOLUTION_CREATED_SUCCESS"),
    BOOK_SOLUTION_UPDATED_SUCCESS("BOOK_SOLUTION_UPDATED_SUCCESS"),
    ACTIVATION_CODE_GENERATED_SUCCESS("ACTIVATION_CODE_GENERATED_SUCCESS"),
    ACTIVATION_CODE_ACTIVATED_SUCCESS("ACTIVATION_CODE_ACTIVATED_SUCCESS"),
    ACTIVATION_CODE_INVALID("ACTIVATION_CODE_INVALID"),
    ACTIVATION_CODE_EXPIRED("ACTIVATION_CODE_EXPIRED"),
    ACTIVATION_CODE_ALREADY_USED("ACTIVATION_CODE_ALREADY_USED"),
    BOOK_ALREADY_OWNED("BOOK_ALREADY_OWNED"),
    BOOK_ACTIVATED_SUCCESS("BOOK_ACTIVATED_SUCCESS"),
    MY_BOOKS_RETRIEVED_SUCCESS("MY_BOOKS_RETRIEVED_SUCCESS"),
    BOOK_CHAPTERS_RETRIEVED_SUCCESS("BOOK_CHAPTERS_RETRIEVED_SUCCESS"),
    BOOK_CHAPTER_CREATED_SUCCESS("BOOK_CHAPTER_CREATED_SUCCESS"),
    BOOK_CHAPTER_UPDATED_SUCCESS("BOOK_CHAPTER_UPDATED_SUCCESS"),
    BOOK_CHAPTER_DELETED_SUCCESS("BOOK_CHAPTER_DELETED_SUCCESS"),
    BOOK_CHAPTER_NOT_FOUND("BOOK_CHAPTER_NOT_FOUND"),

    // Unknown message code
    UNKNOWN("UNKNOWN");

    companion object {
        /**
         * Convert a string message code to MessageCode enum
         * Returns UNKNOWN if the code is not found
         */
        fun fromString(code: String?): MessageCode {
            return entries.find { it.code == code } ?: UNKNOWN
        }
    }
}

